Больше подробностей (часть 2)
htmlacademy-react/1839631-six-cities-8 pull request #10
Opened 2021-11-11 18:24 UTC by DaryaDomoroshchenko

2021-11-13 14:55 UTC, davletbaev requested changes

2021-11-13 14:58 UTC, DaryaDomoroshchenko commented on project/src/components/room-card/room-card.tsx
> +  window.scrollTo(0, 0);
Точно, конечно же в roomPage ))

2021-11-14 11:36 UTC, davletbaev requested changes

2021-11-14 11:36 UTC, davletbaev commented on project/src/hooks/use-map.tsx
> +  }, [mapRef, map, mapCenterPoint]);
Отсюда лучше убрать зависимость mapCenterPoint, потому что карта все равно будет перерисовываться при ее изменении. 
Если eslint ругается, то попробуй добавить переменную initialCenter через useRef, в которую будешь передававать mapCenterPoint при инициализации компонента, и с initialCenter использовать здесь вместо mapCenterPoint

2021-11-14 11:58 UTC, merged