Добавила state в приложение
htmlacademy-react/1839631-six-cities-8 pull request #8
Opened 2021-11-02 21:09 UTC by DaryaDomoroshchenko

Теперь можно переключаться между вкладками с городами, на каждой отображаются соответствующие предложения (списком и на карте)

2021-11-03 06:34 UTC, davletbaev requested changes
В целом код хороший, есть тонкие моменты касающиеся производительности и типов, но это все тоже приходит с опытом.

Важный момент по поводу карты. Ты размещаешь маркеры, но при изменении города ты не убираешь старые маркеры с карты.
Во-первых, это ведет к тому, что при переключении города у тебя на карте остаются маркеры от старого города.

<img width="366" alt="Снимок экрана 2021-11-03 в 09 28 03" src="https://user-images.githubusercontent.com/25131400/140017503-db294232-9a31-4062-8ea4-16216d5ae190.png">

Во-вторых, при каждом ререндере у тебя на карту добавляются одни и те же маркеры.

<img width="489" alt="Снимок экрана 2021-11-03 в 09 29 18" src="https://user-images.githubusercontent.com/25131400/140017627-139740a7-2fca-4dce-a88d-5080110cc355.png">

Так что тебе, прежде чем добавлять новые маркеры, надо очистить старые. Посмотри в сторону компонента L.LayerGroup библиотеки leaflet. Он позволяет создать группу маркеров и очищать ее одной командой.

2021-11-03 06:34 UTC, davletbaev commented on project/src/components/favorites-room-card-list/favorites-room-card-list.tsx
> +  const offersByCities = groupFavoriteOffers(offers);
Опять же ты могла отфильтровать избранные события еще на этапе, когда получала предложения из стора, тебе незачем прогонять полный список предложений через два компонента.

Разделение на города здесь лучше реализовать также как с обычными карточками: 
1. Берешь массив городов, рендеришь контейнер для каждого города
2. Внутри этого массива проходишь по списку предложений и фильтруешь только те, у которых город совпадает с текущим.

Так будет соблюдаться единообразие, и функции c reduce обычно сложны для понимания, в них надо глубоко вникать, чтобы понять как они работают. Это не идет на пользу читабельности кода, поэтому их тоже рекомендую использовать только в случае крайней необходимости.

К тому же ты вообще можешь разбить это все на подкомпоненты и получать избранные офферы из стора по текущему городу прямо в компоненте списка карточек. Тогда, при минимальных трудозатратах в будущем, ты сможешь сделать так, что при изменении списка предложений, будет ререндириться только компонент отвечающий за тот город, где появились новые предложения. Сейчас же при изменении списка офферов у тебя будет ререндериться вся цепочка компонентов.

2021-11-03 06:34 UTC, davletbaev commented on project/src/mocks/room-offers.ts
> +      name: CityName.Amsterdam,
Проблема при использовании enum в том, что с сервера в этом поле будет приходить string, а не enum.
Так что тебе нужен будет дополнительный шаг для трансформации ответа с сервера. В том числе для трансформации типов. А то что ты сделала тут, это просто костыль, чтобы не заморачиваться с типами :)

2021-11-06 12:40 UTC, davletbaev requested changes

2021-11-06 12:40 UTC, davletbaev commented on project/src/components/city-tabs/city-tabs.tsx
> +        onClick={(event) => handleClick(event, city)}
тут ты все равно создаешь новую функцию на каждом рендере. 
Лучше будет переписать через каррирование https://learn.javascript.ru/currying-partials
```jsx
const handleClick = (city) => (event) => {
  event.preventDefault();
  handleClickOnActiveCity(city);
}

<a onClick={ handleClick(city) } />
```

2021-11-06 12:40 UTC, davletbaev commented on project/src/components/map/map.tsx
> +      markerGroup = L.layerGroup().addTo(map);
Тебе не нужно каждый раз создавать этот слой заново. Достаточно создать его один раз, а потом просто добавлять/удалять на нем маркеры.
Можешь использовать useRef для этого.

2021-11-06 12:40 UTC, davletbaev commented on project/src/components/favorites-list/favorites-list.tsx
> +  const isCityInFavorites = (city: CityName) => !!favoriteOffers
Ты можешь здесь сделать проще. 
Чем проверять каждый город на наличие его в избранном, ты можешь просто получить список городов из списка офферов. Например, через `favoriteOffers.map((offer) => offer.city.name)`. Но нужно придумать, как избавиться от дубликатов.

2021-11-06 12:40 UTC, davletbaev commented on project/src/components/header/header.tsx
> +  if (authStatus && authStatus === AuthStatus.Auth) {
Ты можешь эту проверку опять же вынести в коннектор.
А сюда передавать результат одной переменной. 
```js
const mapStateToProps = ({ authStatus }: State) => ({
  isLoggedIn: authStatus && authStatus === AuthStatus.Auth,
});

function Header({ showNav, isLoggedIn }) {
  let nav;

  if (isLoggedIn) {
    ....
```

2021-11-06 12:40 UTC, davletbaev commented on project/src/components/header/header.tsx
> +  if (authStatus && authStatus === AuthStatus.Auth) {
И думаю эти блоки, связанные с авторизацией, лучше вынести в отдельные компоненты, чтобы здесь в хедере не было таких громадных условий.
Например, компоненты UserBlockAuthorized, UserBlockUnAuthorized
и здесь в хедере просто через `{ isLoggedIn ? <UserBlockAuthorized /> : <UserBlockUnAuthorized /> }` использовать

2021-11-06 21:55 UTC, DaryaDomoroshchenko commented on project/src/components/map/map.tsx
> +      markerGroup = L.layerGroup().addTo(map);
Не поняла, как сделать это через useRef, поэтому пока сделала немного по-другому (создание слоя теперь происходит только один раз).

2021-11-06 21:55 UTC, DaryaDomoroshchenko commented
Не поняла, как сделать добавление маркеров в карте через useRef, поэтому пока сделала немного по-другому (создание слоя теперь происходит только один раз).

2021-11-08 06:03 UTC, davletbaev requested changes

2021-11-08 11:48 UTC, merged